### ISSUE TITLE
Installation fails on a fitlet 2: Likely generic Fedora ELN incompatibility

### ISSUE THREAD

**Issue by miabbott** [CentOS/centos-boot#58]
I have a [Fitlet2 device](https://fit-iot.com/web/products/fitlet2/) that I'm trying to install the ELN bootc image (`quay.io/centos-boot/fedora-tier-1:eln`) to.

Using the F39 netinstall ISO from a USB, I used `inst.ks=https://miabbott.fedorapeople.org/centos-boot.ks` to point to a version of https://github.com/CentOS/centos-boot/blob/main/docs/example.ks that has my SSH public key included.

The install proceeds successfully until the "post-installation setup tasks" portion of the install.

I get the following error (transcribed from a physical monitor, so apologies for errors..):

`The command 'ostree admin instutil set-kargs root=UUID=<UUID value> rw' exited with the code -4`

Digging through the `syslog` (attached below), it looks like it could be SELinux denying the operation:

```
19:11:27,208 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:program:Running in chroot '/mnt/sysroot'... ostree admin instutil set-kargs root=UUID=1275dfc6-bad2-4498-8889-e0726e0c900d rw
19:11:27,214 NOTICE audit:AVC avc:  denied  { execute_no_trans } for  pid=4190 comm="python3" path="/usr/bin/ostree" dev="sda5" ino=34006253 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:install_exec_t:s0 tclass=file permissive=1
19:11:27,215 NOTICE kernel:audit: type=1400 audit(1700334687.213:732): avc:  denied  { execute_no_trans } for  pid=4190 comm="python3" path="/usr/bin/ostree" dev="sda5" ino=34006253 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:install_exec_t:s0 tclass=file permissive=1
```

I'll try again with an ELN boot ISO, in case there is SELinux policy differences that may come into play.

**Comment by miabbott** [comment]
[syslog.txt](https://github.com/CentOS/centos-boot/files/13401329/syslog.txt)

**Comment by miabbott** [comment]
I couldn't get the ELN ISOs to boot on bare metal, so I'm unable to determine if that would help this problem.

**Comment by cgwalters** [comment]
The fatal problem in your log seems to be:

```
19:11:27,218 INFO kernel:traps: ostree[4190] trap invalid opcode ip:7f2651c112e3 sp:7ffca6313c70 error:0 in ld-linux-x86-64.so.2[7f2651bf6000+25000]
```
That's...weird... (a few minutes pass)

I bet I know the problem.  Recently ELN was switched to target x86_64-v3 (xref [this commit](https://src.fedoraproject.org/rpms/redhat-rpm-config/c/0c097001d1a56df4e00e8ebdfd15149704dfc07e?branch=rawhide)) whereas main Fedora is still on x86_64-v2.

And the fitlet2 looks like it has an Atom chip which I bet doesn't meet x86_64-v3.  IOW that hardware will not support RHEL10.

You should probably be able to double check this by just trying to run the ELN app image `quay.io/fedoraci/fedora:eln`.

Also I found [this thread](https://www.reddit.com/r/Fedora/comments/11w5req/fedora_on_x8664v3/) has a handy tip; try running `/usr/lib64/ld-linux-x86-64.so.2 --help` on a currently installed system.

**Comment by miabbott** [comment]
> In other words: _that hardware will not support RHEL10_ - this has nothing to do with centos-boot specifically.

Nice find!  I installed Fedora 39 on the device and ran `/usr/lib64/ld-linux-x86-64.so.2 --help` as suggested:

```bash
$ /usr/lib64/ld-linux-x86-64.so.2 --help
...
Subdirectories of glibc-hwcaps directories, in priority order:
  x86-64-v4
  x86-64-v3
  x86-64-v2 (supported, searched)
```

It appears your conclusion is correct; now I need to find newer hardware to test with!
